---
title: "plastics"
author: "Andrea Boskovic"
date: "2/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidytuesdayR)
library(tidyverse)
library(maps)
library(viridis)
```

```{r}
# Read in data
tuesdata <- tidytuesdayR::tt_load('2021-01-26')
plastics <- tuesdata$plastics
```

```{r}
unique(plastics$country)

plastics_clean <- plastics %>%
  filter(country != "EMPTY", year == 2019, 
         parent_company == "The Coca-Cola Company",
         grand_total != 0) %>%
  select(country, year, parent_company, grand_total) %>%
  rename(region = country) 

# Make cleaning country names
plastics_clean$region[27] <- "USA"
plastics_clean$region[16] <- "Nigeria"
plastics_clean$region[7] <- "Ecaudor"
```

```{r}
world_map <- map_data(map = "world"
                      , region = ".")
```

```{r}
plastics_map <- right_join(plastics_clean, world_map, by = "region")
head(plastics_map)
```

```{r}
map_fail <- ggplot(plastics_map, aes(x = long, y = lat, group = group, fill = log(grand_total))) +
  geom_polygon(color = "white") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "World Plastic Pollution from the Coca-Cola Corporation",
       caption = "* Countries in grey have no data",
       fill = "") +
  scale_fill_viridis(option = "magma", direction = -1) 
```

```{r}
counts <- ggplot(plastics_clean, aes(x = reorder(region, grand_total), y = grand_total)) +
  geom_col() +
  labs(x = "Country", y = "Total Plastic",
       title = "Plastic Produced per Country",
       subtitle = "by the Coca-Cola Corporation",
       caption = "Note that all values are nonzero") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggsave(filename = "plastic.jpg", plot = counts, path = "/Users/andreaboskovic/Desktop/tidy_tuesday/tidy_tuesday/2021", dpi=300)
```

```{r}
ggsave(filename = "map_fail.jpg", plot = map_fail, path = "/Users/andreaboskovic/Desktop/tidy_tuesday/tidy_tuesday/2021", dpi=300)
```

